### ISSUE TITLE
Range Slider selection not working properly with stacked bar charts

### ISSUE THREAD

**Issue by felipe-mata** [plotly/R-User-Guide#18]
Hi, 

I've applied the content of this example https://plot.ly/r/range-sliders-selectors/ to a stacked bar chart plot and the bottom chart with the complete preview is not appearing. 

I have checked that changing the plot type to line chart works fine. Can you check the problem with the bar charts?

**Comment by etpinard** [comment]
Range sliders at only available for `scatter` traces at the moment.

**Comment by etpinard** [comment]
Close as this is issue of plotly.js issue. An extension of https://github.com/plotly/plotly.js/pull/336 to me more precise.
